-- Event rosters, post-event outcomes, and partner precinct linkage
-- Run this once in the Supabase SQL editor (Project > SQL Editor > New query),
-- after (or independently of) voter_tracking_migration.sql.
--
-- We don't know the underlying type of the existing `id` primary keys on
-- outreach_events / volunteers / community_partners (no migration history in
-- this repo, and the anon/publishable key can't introspect information_schema).
-- Rather than guess, each table gets its own independent uuid join key that we
-- fully control, so the new FKs below are guaranteed to line up.

alter table outreach_events
  add column if not exists event_uid uuid unique not null default gen_random_uuid();

alter table volunteers
  add column if not exists volunteer_uid uuid unique not null default gen_random_uuid();

alter table community_partners
  add column if not exists partner_uid uuid unique not null default gen_random_uuid();

-- Post-event outcome breakdown: people we could not register, and why.
alter table outreach_events
  add column if not exists could_not_register_no_id integer,
  add column if not exists could_not_register_felony integer,
  add column if not exists could_not_register_other integer;

comment on column outreach_events.could_not_register_no_id is 'Count of contacts who could not register because they lacked valid ID.';
comment on column outreach_events.could_not_register_felony is 'Count of contacts who could not register due to a felony conviction.';
comment on column outreach_events.could_not_register_other is 'Count of contacts who could not register for any other reason (see notes).';

-- Event roster: which volunteers worked which event, in what role, for how long.
create table if not exists event_volunteers (
  id bigint generated by default as identity primary key,
  event_uid uuid references outreach_events(event_uid),
  volunteer_uid uuid references volunteers(volunteer_uid),
  role text,
  hours numeric,
  score integer,
  notes text,
  created_at timestamptz default now()
);

comment on table event_volunteers is 'Roster join table: one row per volunteer who worked a given event, with role/hours/optional 1-5 score.';

-- Partner org <-> precinct/ward linkage (many-to-many, free-text precinct/ward codes
-- to match the loose precinct_ward convention used elsewhere in this app).
create table if not exists partner_precincts (
  id bigint generated by default as identity primary key,
  partner_uid uuid references community_partners(partner_uid),
  precinct_ward text
);

comment on table partner_precincts is 'Which precincts/wards a community partner organization is active in.';

-- RLS: mirrors the permissive public read/insert policy this project already
-- uses (accessed via the anon/publishable key with no auth). Adjust if your
-- other tables use a different policy setup.
alter table event_volunteers enable row level security;
create policy "public read event_volunteers" on event_volunteers for select using (true);
create policy "public insert event_volunteers" on event_volunteers for insert with check (true);

alter table partner_precincts enable row level security;
create policy "public read partner_precincts" on partner_precincts for select using (true);
create policy "public insert partner_precincts" on partner_precincts for insert with check (true);
