-- Voter Tracking feature migration
-- Run this once in the Supabase SQL editor (Project > SQL Editor > New query).
--
-- Adds two quick aggregate-count fields to the existing outreach_events table
-- (for fast per-event tallying, same style as the existing new_registrations field),
-- plus a new voter_contacts table for optional individual-level contact logging.
-- Both feed the new Voter Tracking page — use whichever fits how your team
-- actually logs data in the field, or both.

-- 1. Quick aggregate counts on each event/canvass
alter table outreach_events
  add column if not exists found_already_registered integer,
  add column if not exists found_inactive integer;

comment on column outreach_events.found_already_registered is 'Count of contacts at this event who did not realize they were already registered to vote.';
comment on column outreach_events.found_inactive is 'Count of contacts at this event who did not realize their registration had gone inactive.';

-- 2. Individual voter contact log (optional, more granular alternative)
create table if not exists voter_contacts (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  contact_date date,
  precinct_ward text,
  event_name text,
  contact_name text,
  outcome text check (outcome in (
    'New Registration',
    'Already Registered',
    'Inactive - Reactivated',
    'Inactive - Not Reactivated',
    'Declined'
  )),
  notes text
);

comment on table voter_contacts is 'Individual-level voter contact log, one row per person contacted during an event/canvass. Optional alternative/complement to the aggregate counts on outreach_events.';

-- RLS: mirrors the permissive public read/insert policy this project already
-- uses on its other tables (accessed via the anon/publishable key with no auth).
-- If your other tables use different policy names or a stricter setup, adjust
-- accordingly before running.
alter table voter_contacts enable row level security;

create policy "public read voter_contacts" on voter_contacts
  for select using (true);

create policy "public insert voter_contacts" on voter_contacts
  for insert with check (true);
